/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.AppControl;
import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author moudy
 */

public class Bookframe extends javax.swing.JFrame {
  public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookframe("mask").setVisible(true);
            }
        });
    }
    private String name;//movie
    private DefaultTableModel m;//seats
    ArrayList<String> it;//combo seat
    AppControl c;
    private int i, allowed = 0;
    final String[] seating = {
            "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10",
            "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10",
            "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10"
        };
    /**
     * Creates new form Bookframe
     */
//remove duplicates from arrayList
    @SuppressWarnings("hiding")

    public Bookframe(String n) {
        this.name = n;
//this.name="The Matrix";
        initComponents();
        c = new AppControl();
        it = new ArrayList<>();
        m = (DefaultTableModel) sout.getModel();
         ArrayList<String> originalseat = new ArrayList<>();
        for (String q : seating) {
            originalseat.add(q);
        }
/////////////////////////////////////////////////////////////////////////
        sp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent e) {
                statechange(e);
            }
        });
//////////////////////////////////////////////////////////////////////
        mn.setText(name);
        d.setText(c.getMoviedesc(name));
        scr.setText("Theater : " + c.MovietoTheater(name).getID());
        t.setText(c.getTheatertime(c.MovietoTheater(name)));
        im.setIcon(c.display(name));
        pr.setText("" + c.getMoviePrice(name));
        //////////
        sp.setModel(new SpinnerNumberModel(1, 1, 31 - c.gettakenseatnb(c.MovietoTheater(name)), 1));//max and min 
        ///////////
        ArrayList<String> takenseat = c.gettakenseat(c.MovietoTheater(name));
        ArrayList<String> finalseat=originalseat;
        
        if(takenseat!=null){//ERROR
         finalseat = c.removeDuplicates(originalseat, takenseat);
        }
        for (int j = 0; j < finalseat.size(); j++) {
            s.addItem(finalseat.get(j));
            it.add(finalseat.get(j));
        }

        del.setVisible(false);
        tot.setText(("" + (c.getMoviePrice(name) * Double.parseDouble(sp.getValue().toString()))));

    }

    private void statechange(javax.swing.event.ChangeEvent e) {
        tot.setText(("" + (c.getMoviePrice(name) * Double.parseDouble(sp.getValue().toString()))));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mn = new javax.swing.JLabel();
        t = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pr = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sp = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        s = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        im = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sout = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tot = new javax.swing.JFormattedTextField();
        scr = new javax.swing.JLabel();
        wesrdgvbh = new javax.swing.JScrollPane();
        d = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mn.setText("movie name");

        t.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t.setText("time");

        jLabel4.setText("ticket price:");

        pr.setText("price");

        jLabel6.setText("number of tickets");

        jLabel7.setText("choose your desired seats");

        add.setText("add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\moudy\\Documents\\NetBeansProjects\\Movie_Booking\\seat.png")); // NOI18N

        im.setMaximumSize(new java.awt.Dimension(120, 120));
        im.setMinimumSize(new java.awt.Dimension(120, 120));
        im.setPreferredSize(new java.awt.Dimension(120, 120));

        jButton3.setText("Book/Pay");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        del.setText("del");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        sout.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sout.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(sout);

        jLabel2.setText("total: $");

        tot.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        scr.setText("theater");

        d.setEditable(false);
        d.setColumns(20);
        d.setLineWrap(true);
        d.setRows(5);
        wesrdgvbh.setViewportView(d);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(pr)
                        .addGap(86, 86, 86)
                        .addComponent(scr))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(im, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mn, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(wesrdgvbh, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tot, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(im, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(wesrdgvbh, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t)
                            .addComponent(jLabel4)
                            .addComponent(pr)
                            .addComponent(scr))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(tot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(add)
                                    .addComponent(del))
                                .addGap(8, 8, 8)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if (Integer.parseInt(sp.getValue().toString()) > allowed) {
            allowed++;
            if (i == 29) {
                add.setVisible(false);
            }
            del.setVisible(true);
            m.addRow(new String[]{s.getSelectedItem().toString()});
            it.remove(s.getSelectedItem().toString());
            s.removeAllItems();
            for (String x : it) {
                s.addItem(x);
            }
            i = m.getRowCount();
            it.sort(Comparator.naturalOrder());
        }
    }//GEN-LAST:event_addActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        if (sout.getSelectedRow() != -1) {
            if (i == 1) {
                del.setVisible(false);
            }
            String q = sout.getValueAt(sout.getSelectedRow(), 0).toString();
            allowed--;

            m.removeRow(sout.getSelectedRow());
            s.removeAllItems();
            it.add(q);
            for (String x : it) {
                s.addItem(x);
            }
            i = m.getRowCount();

            it.sort(Comparator.naturalOrder());
        } else
            JOptionPane.showMessageDialog(this, "please select a seat before deleting", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_delActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (m.getRowCount() != 0) {
            if ((JOptionPane.showConfirmDialog(this, "Your total is " + tot.getText() + "\nDo you wish to finalise the payment?", "Confirmation", JOptionPane.YES_NO_OPTION)) == 0) {

                c.addpay(Main_screen.user, tot.getText());

                String tek[] = new String[m.getRowCount()];

                for (int y = 0; y < m.getRowCount(); y++) {
                    String chair = m.getValueAt(y, 0).toString();
                    tek[y] = chair;
                  
                }

                
                c.addbook(Main_screen.user, "" + c.getusercard(Main_screen.user),
                        "" + c.getTheaterID(c.MovietoTheater(name)),
                        "" + c.getTheatercap(c.MovietoTheater(name)), tek,
                        c.getTheatertime(c.MovietoTheater(name)),
                        name, c.getMoviedesc(name), "" + c.getMoviePrice(name), c.getMovieimg(c.findMovie(name)),
                        tot.getText());
            }

        } else {
            JOptionPane.showMessageDialog(this, "please choose seats before proceeding");
        }
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
 
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextArea d;
    private javax.swing.JButton del;
    private javax.swing.JLabel im;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mn;
    private javax.swing.JLabel pr;
    private javax.swing.JComboBox<String> s;
    private javax.swing.JLabel scr;
    private javax.swing.JTable sout;
    private javax.swing.JSpinner sp;
    private javax.swing.JLabel t;
    private javax.swing.JFormattedTextField tot;
    private javax.swing.JScrollPane wesrdgvbh;
    // End of variables declaration//GEN-END:variables
}
