/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.AppControl;
import Model.Movie;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author moudy
 */
public class Main_screen extends javax.swing.JFrame {

    AppControl c;
    protected static boolean logged = false;
    protected static String user = "";
    private final int nb;

    /**
     * Creates new form Main_screen
     */
    public Main_screen() {
      
        initComponents();
        c = new AppControl(); 
        nb=c.getScreennb();
        obt.setVisible(false);
        
        L1.setText("");
        L2.setText("");
        L3.setText("");
        
        P1.setText("");
        P2.setText("");
        P3.setText("");
        
        prev.setVisible(false);
        next.setVisible(false);
        
        if (nb > 3) {
            next.setVisible(true);
        }HashMap mp=c.getScreentheaters();
        HashMap mnp=c.getScreentheaters();//check
        ArrayList<String> mv = new ArrayList<>(mp.values());
        ArrayList<Movie> mvs = new ArrayList<>();
        for(String x: mv){
            mvs.add(c.findMovie(x));
       
        
       if (nb == 1) {
            P1.setIcon(c.display(mv.get(0)));
            L1.setText(mv.get(0));
        } else if (nb == 2) {
            P1.setIcon(c.display(mv.get(0)));
            L1.setText(mv.get(0));
            
            P2.setIcon(c.display(mv.get(1)));
            L2.setText(mv.get(1));
        } else if (nb >= 3) {
            P1.setIcon(c.display(mv.get(0)));
            L1.setText(mv.get(0));
            
            P2.setIcon(c.display(mv.get(1)));
            L2.setText(mv.get(1));
            
            
            P3.setIcon(c.display(mv.get(2)));
            L3.setText(mv.get(2));}
    
    }                                    

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logbt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        g = new javax.swing.JLabel();
        obt = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        next = new javax.swing.JButton();
        prev = new javax.swing.JButton();
        L1 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        P1 = new javax.swing.JLabel();
        P3 = new javax.swing.JLabel();
        P2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        logbt.setBackground(new java.awt.Color(204, 0, 0));
        logbt.setForeground(new java.awt.Color(255, 255, 255));
        logbt.setText("Login");
        logbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Welcome");

        g.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        g.setForeground(new java.awt.Color(255, 255, 0));
        g.setText("Guest");

        obt.setBackground(new java.awt.Color(204, 0, 0));
        obt.setText("Logout");
        obt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(g)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logbt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(obt)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(g))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logbt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(obt)))
                .addContainerGap())
        );

        next.setBackground(new java.awt.Color(0, 51, 255));
        next.setText("next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        prev.setBackground(new java.awt.Color(0, 0, 255));
        prev.setText("prev");
        prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevActionPerformed(evt);
            }
        });

        L1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L1.setForeground(new java.awt.Color(153, 255, 255));
        L1.setText("jLabel3");
        L1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mh(evt);
            }
        });
        L1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m1(evt);
            }
        });

        L3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L3.setForeground(new java.awt.Color(0, 255, 255));
        L3.setText("jLabel3");
        L3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mh(evt);
            }
        });
        L3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m3(evt);
            }
        });

        L2.setBackground(new java.awt.Color(204, 0, 0));
        L2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L2.setForeground(new java.awt.Color(102, 255, 255));
        L2.setText("jLabel3");
        L2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mh(evt);
            }
        });
        L2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m2(evt);
            }
        });

        P1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mh(evt);
            }
        });
        P1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m1(evt);
            }
        });

        P3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mh(evt);
            }
        });
        P3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m3(evt);
            }
        });

        P2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mh(evt);
            }
        });
        P2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m2(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(prev)
                        .addGap(18, 18, 18)
                        .addComponent(next))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(P3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 342, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prev)
                    .addComponent(next))
                .addContainerGap())
        );

        desc.setEditable(false);
        desc.setColumns(20);
        desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        desc.setLineWrap(true);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void logbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbtActionPerformed
        Login a = new Login();
        a.setVisible(true);
    }//GEN-LAST:event_logbtActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        HashMap mp=c.getScreentheaters();
        
        ArrayList<String> mv = new ArrayList<>(mp.values());//keys
        
        if (nb == 4) {
            P1.setIcon(c.display(mv.get(3)));
            L1.setText((mv.get(3)));
        } else if (nb == 5) {
            P1.setIcon(c.display(mv.get(3)));
            L1.setText(mv.get(3));
            
            P2.setIcon(c.display(mv.get(4)));
            L2.setText(mv.get(4));
        } else if (nb == 6) {
            P1.setIcon(c.display(mv.get(3)));
            L1.setText(mv.get(3));
            
            P2.setIcon(c.display(mv.get(4)));
            L2.setText(mv.get(4));
            
            P3.setIcon(c.display(mv.get(5)));
            L3.setText(mv.get(5));
        }
        next.setVisible(false);
        prev.setVisible(true);
    }//GEN-LAST:event_nextActionPerformed

    private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
        
         HashMap mp=c.getScreentheaters();
        
        ArrayList<String> mv = new ArrayList<>(mp.values());
        ArrayList<Movie> mvs = new ArrayList<>();
       if (nb == 1) {
            P1.setIcon(c.display(mv.get(0)));
            L1.setText(mv.get(0));
        } else if (nb == 2) {
            P1.setIcon(c.display(mv.get(0)));
            L1.setText(mv.get(0));
            
            P2.setIcon(c.display(mv.get(1)));
            L2.setText(mv.get(1));
        } else if (nb >= 3) {
            P1.setIcon(c.display(mv.get(0)));
            L1.setText(mv.get(0));
            
            P2.setIcon(c.display(mv.get(1)));
            L2.setText(mv.get(1));
            
            
            P3.setIcon(c.display(mv.get(2)));
            L3.setText(mv.get(2));}
    
        prev.setVisible(false);
        next.setVisible(true);
    }//GEN-LAST:event_prevActionPerformed

    private void mh(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mh
        Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        P1.setCursor(cursor);
        P2.setCursor(cursor);
        P3.setCursor(cursor);
        
        L1.setCursor(cursor);
        L2.setCursor(cursor);
        L3.setCursor(cursor);
        
        if((JLabel)evt.getSource()==P1||(JLabel)evt.getSource()==L1){
            String txt=L1.getText().toString();
         desc.setText(c.getMoviedesc(txt));
        }
        if((JLabel)evt.getSource()==P2||(JLabel)evt.getSource()==L2){
            String txt=L2.getText().toString();
         desc.setText(c.getMoviedesc(txt));
        }
        if((JLabel)evt.getSource()==P3||(JLabel)evt.getSource()==L3){
            String txt=L3.getText().toString();
         desc.setText(c.getMoviedesc(txt));
        }
        
    }//GEN-LAST:event_mh

    private void m1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m1
        
        if(!logged){
           JOptionPane.showMessageDialog(this, "Please login before continuing");
        } 
       if(c.getTheatercap(c.MovietoTheater(L1.getText()))==0&&logged){
            JOptionPane.showMessageDialog(this, "this movie is fully booked");
            
        }else {
           String q=L1.getText().toString();
           Bookframe bk = new Bookframe(q); 
        bk.setVisible(true);
       }
    }//GEN-LAST:event_m1

    private void obtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtActionPerformed
        Main_screen m = new Main_screen();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_obtActionPerformed
    
    
    private void m2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m2
         
        if(!logged){
       JOptionPane.showMessageDialog(this, "Please login before continuing");
        }
        
        if(c.getTheatercap(c.MovietoTheater(L2.getText()))==0&&logged){
            JOptionPane.showMessageDialog(this, "this movie is fully booked");
            Bookframe bk = new Bookframe(L2.getText());
        bk.setVisible(true);
        }
    }//GEN-LAST:event_m2

    private void m3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m3
        if(!logged){
        JOptionPane.showMessageDialog(this, "Please login before continuing");
        }
        if(c.getTheatercap(c.MovietoTheater(L3.getText()))==0&&logged){
            JOptionPane.showMessageDialog(this, "this movie is fully booked");
            Bookframe bk = new Bookframe(L3.getText());
        bk.setVisible(true);
        }
       
    }//GEN-LAST:event_m3

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel P1;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel P3;
    private javax.swing.JTextArea desc;
    protected static javax.swing.JLabel g;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    protected static javax.swing.JButton logbt;
    private javax.swing.JButton next;
    protected static javax.swing.JButton obt;
    private javax.swing.JButton prev;
    // End of variables declaration//GEN-END:variables
}
